- name: infrastructure
  description: "Infrastructure repo is the warehouse operated and maintained by Infrastructure sig, including but not limited to CI access control, release platform, official website, etc."
  type: privacy
- name: openubmc-ci
  description: "The openubmc-ci repo is the repository for managing CI access control"
  type: privacy
- name: website
  description: "openUBMC official website"
  type: privacy
- name: nginx
  description: "The nginx repo is the repository for managing nginx access control"
  type: privacy
- name: conan-auth-proxy
  description: "conan-auth-proxy"
  type: privacy
- name: software-center
  description: "Software Center Backend Services for openUBMC"
  type: privacy
- name: software-center-importer
  description: "Software Center Importer Backend Services for openUBMC"
  type: privacy