name: Infrastructure
description: "负责openUBMC社区基础设施建设和维护"
created_on: '2024-12-31'
mailing_list: infrastructure@public.openubmc.cn
meeting_url: https://etherpad.openubmc.cn/p/infrastructure
maintainers:
  - gitcode_id: georgecao
    name: 曹志
  - gitcode_id: zengchen1024
    name: 陈曾
committers:
  - gitcode_id: weixin_43493709
    name: 朱超
  - gitcode_id: persimmonzzz
    name: 黄世俊
  - gitcode_id: LiYanghang00
    name: 李洋行
  - gitcode_id: ddll1234
    name: 野岱琳
repositories:
  - openUBMC/infrastructure
  - openUBMC/openubmc-ci
  - openUBMC/website
  - openUBMC/website-backend
  - openUBMC/nginx
  - openUBMC/conan-auth-proxy
  - openUBMC/software-center
  - openUBMC/software-center-importer
meeting_agenda:
  - "1、讨论和接纳社区对基础设施的诉求。"
  - "2、讨论和评审基础设施服务的技术方案。"
  - "3、讨论和评审基础设施的长期规划。"
